# Generated by Django 5.0.6 on 2024-05-21 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TSC_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_no', models.CharField(blank=True, max_length=50, null=True)),
                ('trip_date', models.DateField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=150, null=True)),
                ('guest', models.CharField(blank=True, max_length=150, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('trip_charge_type', models.CharField(blank=True, max_length=20, null=True)),
                ('fixed_hour_charge', models.FloatField(blank=True, default=0.0, null=True)),
                ('max_hour', models.FloatField(blank=True, default=0.0, null=True)),
                ('extra_hour_charge', models.FloatField(blank=True, default=0.0, null=True)),
                ('fixed_charge', models.FloatField(blank=True, default=0.0, null=True)),
                ('max_kilometer', models.FloatField(blank=True, default=0.0, null=True)),
                ('extra_charge', models.FloatField(blank=True, default=0.0, null=True)),
                ('starting_km', models.FloatField(blank=True, default=0.0, null=True)),
                ('ending_km', models.FloatField(blank=True, default=0.0, null=True)),
                ('trip_end_date', models.DateField(blank=True, null=True)),
                ('starting_place', models.CharField(blank=True, max_length=150, null=True)),
                ('starting_time', models.TimeField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=150, null=True)),
                ('time_of_arrival', models.TimeField(blank=True, null=True)),
                ('kilometers', models.FloatField(blank=True, default=0.0, null=True)),
                ('permit', models.FloatField(blank=True, default=0.0, null=True)),
                ('toll', models.FloatField(blank=True, default=0.0, null=True)),
                ('parking', models.FloatField(blank=True, default=0.0, null=True)),
                ('entrance', models.FloatField(blank=True, default=0.0, null=True)),
                ('guide_fee', models.FloatField(blank=True, default=0.0, null=True)),
                ('other_charges', models.FloatField(blank=True, default=0.0, null=True)),
                ('advance', models.FloatField(blank=True, default=0.0, null=True)),
                ('trip_fixed_charge', models.FloatField(blank=True, default=0.0, null=True)),
                ('trip_extra_charge', models.FloatField(blank=True, default=0.0, null=True)),
                ('trip_charge', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_trip_expense', models.FloatField(blank=True, default=0.0, null=True)),
                ('trip_days', models.IntegerField(blank=True, default=1, null=True)),
                ('balance', models.FloatField(blank=True, default=0.0, null=True)),
                ('bill_qr', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxi_app.driver')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TSC_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_type', models.CharField(blank=True, max_length=100, null=True)),
                ('exp_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('exp_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('Trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxi_app.tsc_form')),
            ],
        ),
        migrations.CreateModel(
            name='TripRideHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('hours', models.CharField(blank=True, default=0.0, max_length=20, null=True)),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxi_app.tsc_form')),
            ],
        ),
    ]
