# Generated by Django 5.0.6 on 2024-05-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsc_form',
            name='guide_fee_place',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tsc_form',
            name='other_charge_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
